# ADD student 1
POST http://localhost:8080/rest-web/api/student
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiJ9.xMC06ydl5F70p_XgUrkkc2w7857KXN4QAcV4kmu0Usby9pqQq4Ax2RMMpbkLkhSJjW_2epnRg2ppD6g1j3yQKw

name=ignacy radlinski&studentCardId=123456&faculty=WIET&semester=7&courses=JIMP&avatar=12354234352134323

###

# ADD student 1 with not permitted faculty name
POST http://localhost:8080/rest-web/api/student
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiJ9.xMC06ydl5F70p_XgUrkkc2w7857KXN4QAcV4kmu0Usby9pqQq4Ax2RMMpbkLkhSJjW_2epnRg2ppD6g1j3yQKw

name=ignacy radlinski&studentCardId=123456&faculty=WIMIR&semester=7&courses=JIMP&avatar=12354234352134323

###


# ADD student 2
POST http://localhost:8080/rest-web/api/student
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiJ9.xMC06ydl5F70p_XgUrkkc2w7857KXN4QAcV4kmu0Usby9pqQq4Ax2RMMpbkLkhSJjW_2epnRg2ppD6g1j3yQKw

name=agnieszka miszkurka&studentCardId=654321&faculty=EAIIB&semester=7&courses=SOA&avatar=76453435324353214

###

# ADD student 3
POST http://localhost:8080/rest-web/api/student
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiJ9.xMC06ydl5F70p_XgUrkkc2w7857KXN4QAcV4kmu0Usby9pqQq4Ax2RMMpbkLkhSJjW_2epnRg2ppD6g1j3yQKw

name=jan kowalski&studentCardId=085838&faculty=WIET&semester=6&courses=SOA&avatar=12354234352134323

###

# ADD with missing name parameter
POST http://localhost:8080/rest-web/api/student
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiJ9.xMC06ydl5F70p_XgUrkkc2w7857KXN4QAcV4kmu0Usby9pqQq4Ax2RMMpbkLkhSJjW_2epnRg2ppD6g1j3yQKw

studentCardId=333333&faculty=EAIIB&semester=7&courses=SOA&courses=JIMP&avatar=12354234352134323

###


# list
GET http://localhost:8080/rest-web/api/student
Accept: application/json

###

# list with semester filter
GET http://localhost:8080/rest-web/api/student?semester=6
Accept: application/json

###

# list with faculty filter
GET http://localhost:8080/rest-web/api/student?faculty=WIET
Accept: application/json

###

# list with course filter
GET http://localhost:8080/rest-web/api/student?course=SOA
Accept: application/json

###

# list with semester and faculty filter
GET http://localhost:8080/rest-web/api/student?faculty=EAIIB&course=SOA
Accept: application/json

###


# list with semester and faculty and course filter
GET http://localhost:8080/rest-web/api/student?faculty=WIET&semester=6&course=SOA
Accept: application/json

###

# getById OK
GET http://localhost:8080/rest-web/api/student/123456
Accept: application/json

###


# getById NOT FOUND
GET http://localhost:8080/rest-web/api/student/99999
Accept: application/json

###

# EDIT student 1 UNAUTHORIZED
PUT http://localhost:8080/rest-web/api/student/123456
Accept: application/json
Content-Type: application/x-www-form-urlencoded

faculty=WIET&semester=8&courses=SOA&courses=JIMP

###



# LOGIN
POST http://localhost:8080/rest-web/api/auth/login
Accept: application/json
Content-Type: application/x-www-form-urlencoded

login=admin&password=admin

###


# EDIT student 1
PUT http://localhost:8080/rest-web/api/student/123456
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiJ9.xMC06ydl5F70p_XgUrkkc2w7857KXN4QAcV4kmu0Usby9pqQq4Ax2RMMpbkLkhSJjW_2epnRg2ppD6g1j3yQKw

faculty=EAIIB&semester=6&courses=SOA&courses=JIMP

###


# DELETE

DELETE http://localhost:8080/rest-web/api/student/123456
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiJ9.xMC06ydl5F70p_XgUrkkc2w7857KXN4QAcV4kmu0Usby9pqQq4Ax2RMMpbkLkhSJjW_2epnRg2ppD6g1j3yQKw

###
